# taken from https://github.com/yonaskolb/XcodeGen
name: Sample
options:
  bundleIdPrefix: "your.reverse.domain"
targets:
  Sample:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sample]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
#    dependencies:
#      - target: MyFramework
#      - carthage: Alamofire
#      - framework: Vendor/MyFramework.framework
#      - sdk: Contacts.framework
#      - sdk: libc++.tbd
#  MyFramework:
#    type: framework
#    platform: iOS
#    sources: [MyFramework]
