import Foundation
import UIKit

/**
 generated by DesignToCode automatically. Usually NO NEED TO EDIT this file.
 */

struct Dtc {
    struct config {
        static var TravelHotels: ViewConfig {
            get {
                return TravelHotelsConfig()
            }
        }
        static var TravelRestaurants: ViewConfig {
            get {
                return TravelRestaurantsConfig()
            }
        }
        static var TravelReservation: ViewConfig {
            get {
                return TravelReservationConfig()
            }
        }
        static var TravelCity: ViewConfig {
            get {
                return TravelCityConfig()
            }
        }
        static var TravelCities: ViewConfig {
            get {
                return TravelCitiesConfig()
            }
        }
        static var SocialConversation: ViewConfig {
            get {
                return SocialConversationConfig()
            }
        }
    }
}
